routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login-show', 'DashboardController@login_view')->name('login.show');
Route::post('login-web','DashboardController@login_web')->name('login.web');
Auth::routes();

Route::group(['prefix' => '/','middleware' => 'auth:web'], function () {

	Route::get('error-404',function () {
	    return view('error404');
	})->name('error.404');

	Route::get('/', function(){
		return redirect('dashboard');
	});
	
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');
	Route::post('dashboard', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard/promo-bulanan', 'DashboardController@promoKedatangan')->name('dashboard.promo');
	Route::get('dashboard/kedatangan','DashboardController@kedatangan')->name('dashboard.kedatangan');
	Route::get('logout','DashboardController@logout');
	Route::group(['middleware' => 'auth.admin'], function () {
		Route::get('user-admin','AdminController@index');
		Route::get('user-add','AdminController@create');
		Route::post('user-store','AdminController@store')->name('user.store');
		Route::get('user-edit/{id}','AdminController@edit')->name('user.edit');
		Route::post('user-update/{id}','AdminController@update')->name('user.update');
		Route::get('user-deleted/{id}','AdminController@destroy')->name('user.destroy');

		Route::get('setting','SettingController@index');
		Route::post('setting-update/{id}','SettingController@update')->name('setting.update');
		Route::post('setting-keywoo','SettingController@wookey')->name('setting.wookey');
		Route::resource('pasien', 'PasienController');
		Route::post('pasien-add/{id}','PasienController@jadikanPasien')->name('pasien.add');
		
		Route::resource('kategory','KategoryController');
		Route::resource('reminder', 'ReminderController');
		Route::resource('promo','PromoController');

		Route::post('promo-send/{id}','PromoController@kirimPromo')->name("promo.send");

		Route::get("laporan/logPromo",'LaporanController@logPromo')->name("log.promo");
		Route::get("laporan/logRemin",'LaporanController@logReminder')->name("log.remin");



	});
	
});

app/Http/Controllers/Api/PromoController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use ImageOptimizer;
use App\NotifPasien;
use App\ProsesPasien;
use App\KategoryPasien;
use App\JobPromo;
use Auth;
use App\LogPromo;
use Illuminate\Support\Str;
use App\Http\Resources\LogCollection;

class PromoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $promo = NotifPasien::where('is_deleted',0);

        if ($request->has('jenis') && $request->jenis != "all") {
            # code...
            $promo = $promo->where('jenis', $request->jenis);
        }
        if($request->_q != '')
        {
            $q = $request->_q;
            # code...
            $promo =$promo->whereRaw("upper(nama) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(no_wa) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(usia_kehamilan) LIKE '%".strtoupper($q)."%'");
        }
        $promo = $promo->orderBy("created_at","desc")->paginate(7);
        return response()->json(compact('promo'), 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $model = new NotifPasien;
        $model->judul = $request->name;
        $model->keterangan = $request->deskription;
        $model->created_by = Auth::user()->id;
        $model->updated_by = Auth::user()->id;
        if($request->has('gambar')){
         
            $path = public_path();
            $host = $_SERVER['SERVER_NAME'];
            $destination_dir = $path."/uploads/promo/";
            $base_filename = basename($_FILES["gambar"]["name"]);
            $temp = explode(".", $_FILES["gambar"]["name"]);
            $newfilename = round(microtime(true)) . '.' . end($temp);
            $target_file = $destination_dir . $newfilename;
            if(move_uploaded_file($_FILES["gambar"]["tmp_name"], $target_file)){
                $model->gambar = "uploads/promo/".$newfilename;
            }
         
        }
        if($model->save()){
             return response()->json(compact('model'), 200);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

        //
        try {
            $model = NotifPasien::findOrFail((int)$request->id);
            $model->judul = $request->judul;
            $model->keterangan = $request->keterangan;
            $model->start = $request->start;
            $model->end = $request->end;
            $model->updated_by = Auth::user()->id;
            if($request->has('gambar')){
                 $model->gambar = $request->gambar;
            }
            $model->save();
            return response()->json(['message' => 'Updated Success','data' =>  $model ], 200);
            
        } catch (Exception $e) {
            return response()->json(['message' => 'error. '.$e->getMassage() ,'data' => $e ], 500);
        }
        return response()->json(['message' => 'Something went wrong. '], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        $model = NotifPasien::findOrFail($request->id);
        $model->is_deleted = 1;
        $model->save();
        //
    }

    public function sendpromo(Request $request){
        // $model = NotifPasien::findOrFail((int)$request->id);
        // $response;

        // if($model->jenis == 'bumil'){
        //     $pasiens = ProsesPasien::where(['is_deleted' => 0,'jenis' => $model->jenis])
        //     ->Where('usia_kehamilan_calc',">=",$model->start)
        //     ->Where('usia_kehamilan_calc',"<=",$model->end);
        //     if($request->has('is_pasien')){
        //         $pasiens = $pasiens->where('is_pasien', $request->is_pasien);
        //     }


        //     foreach ($pasiens->get() as $key => $value) {
        //         # code...
        //         $log = new LogPromo;
        //         $log->to = json_encode($value);
        //         $log->log = json_encode($model);
        //         $log->created_by = Auth::user()->name;
        //         if($log->save()){
        //             $judul_konten = '*'.$model->judul.'*'.' - '.$model->keterangan;
        //             $gambar = isset($model->gambar) ? $model->gambar : null;
        //             $response = self::sendWa($value->no_wa,$judul_konten,$gambar);
        //         }
        //     }
            
        // }else{
        //     $pasiens = ProsesPasien::where(['is_deleted' => 0,'jenis' => $model->jenis]);
        //      if($request->has('is_pasien')){
        //         $pasiens = $pasiens->where('is_pasien', $request->is_pasien);
        //     }
        //     foreach ($pasiens->get() as $key => $value) {
        //         # code...
        //         $log = new LogPromo;
        //         $log->to = json_encode($value);
        //         $log->log = json_encode($model);
        //         $log->created_by = Auth::user()->name;
        //         if($log->save()){
        //             $judul_konten = '*'.$model->judul.'*'.' - '.$model->keterangan;
        //             $gambar = isset($model->gambar) ? $model->gambar : null;
        //             $response = self::sendWa($value->no_wa,$judul_konten,$gambar);
        //         }
        //     }

        // }

          $model = new JobPromo;
          $model->kategori_id = $request->kategori_id;
          $model->promo_id =  $request->id;
          if($model->save())
          return response()->json($model,200);

    }

    public function kategoriPasien(){
       $kategory = KategoryPasien::where('is_deleted','0')->get();
       return response()->json($kategory, 200);
    }

    public function sendWa($to,$pesan,$gambar=null){

        $curl = curl_init();
        $url = 'http://116.203.191.58/api/async_send_message';
        $param["phone_no"] = Str::startsWith($to, '0') ?  Str::replaceFirst("0","+62",$to) : $to;

        $param["key"] = env("KEY_WOO_API");
        $param["message"] = $pesan;
        if(isset($gambar) && $gambar != ""){
            $url = "http://116.203.191.58/api/async_send_image_url";
            $param["url"]  = url('')."/../".$gambar;    
        } 
        curl_setopt_array($curl, array(
          CURLOPT_URL => $url,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'POST',
          CURLOPT_POSTFIELDS => json_encode($param),
          CURLOPT_HTTPHEADER => array(
            'Content-Type: application/json'
          ),
        ));
        $response = curl_exec($curl);
        $err = curl_error($curl);
        if ($err) {
          Log::info("cURL Error #:" . $err);
          return null;
        }
        curl_close($curl);
        return $response;
    }

    public function logpromo(Request $request)
    {

        $promo = LogPromo::make();
        if($request->_q != '')
        {
            $q = $request->_q;
            # code...
            $promo =$promo->whereRaw("upper(to) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(log) LIKE '%".strtoupper($q)."%'");
        }
        $promo = new LogCollection($promo->orderBy("created_at","desc")->paginate(7));
        return response()->json(compact('promo'), 200);
    }

}

app/Http/Controllers/PromoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use App\NotifPasien;
use App\KategoryPasien;
use Response;
use Auth;
use App\Http\Controllers\Api;
use App\LogPromo;
use App\JobPromo;

class PromoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if($request->ajax()){
            $model = NotifPasien::where('is_deleted','0');
            $datatables = Datatables::of($model)
            ->addColumn('action', function ($model) {
                return '
                        <a href="'.route('promo.show',$model->id).'" class="btn btn-primary btn-circle btn-sm">
                            <i class="fas fa-eye"></i>
                        </a>&nbsp;<a href="'.route('promo.edit',$model->id).'" class="btn btn-primary btn-circle btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>&nbsp;
                        <button class="btn btn-danger btn-circle btn-sm btn-hapus" data-id="'.$model->id.'">
                            <i class="fas fa-trash"></i>
                        </button>'; 
            });
            return $datatables->make(true);
        }

        return view('promo.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('promo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());
        
        $model = new NotifPasien;
        $model->judul = $request->name;
        $model->keterangan = $request->deskription;
        $model->created_by = Auth::user()->id;
        $model->updated_by = Auth::user()->id;
        if($request->has('gambar')){
         
            $path = public_path();
            $host = $_SERVER['SERVER_NAME'];
            $destination_dir = $path."/uploads/promo/";
            $base_filename = basename($_FILES["gambar"]["name"]);
            $temp = explode(".", $_FILES["gambar"]["name"]);
            $newfilename = round(microtime(true)) . '.' . end($temp);
            $target_file = $destination_dir . $newfilename;
            if(move_uploaded_file($_FILES["gambar"]["tmp_name"], $target_file)){
                $model->gambar = "uploads/promo/".$newfilename;
            }
         
        }
        if($model->save()){
            return \Redirect::to('/promo');
        }
        return redirect()->back()->withErrors([
            'others' => "Something went wrong.",
        ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $kategory = KategoryPasien::where('is_deleted','0')->get();
        $model = NotifPasien::findOrFail($id);
        return view('promo.show',compact('model','kategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $model = NotifPasien::findOrFail($id);
        return view('promo.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // dd($request->all());
        $model = NotifPasien::findOrFail($id);
        $model->judul = $request->name;
        $model->keterangan = $request->deskription;
        $model->updated_by = Auth::user()->id;
        if($request->has('gambar')){
         
            $path = public_path();
            $host = $_SERVER['SERVER_NAME'];
            $destination_dir = $path."/uploads/promo/";
            $base_filename = basename($_FILES["gambar"]["name"]);
            $temp = explode(".", $_FILES["gambar"]["name"]);
            $newfilename = round(microtime(true)) . '.' . end($temp);
            $target_file = $destination_dir . $newfilename;
            if(move_uploaded_file($_FILES["gambar"]["tmp_name"], $target_file)){
                $model->gambar = "uploads/promo/".$newfilename;
            }
         
        }
        if($model->save()){
            return \Redirect::to('/promo');
        }
        return redirect()->back()->withErrors([
            'others' => "Something went wrong.",
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {
            $model = NotifPasien::findOrFail($id);
            $model->is_deleted = 1;
            if($model->save()){
                return Response::json(['status' => 'S','pesan' => 'Berhasil menghapus data.']);
            }
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        } catch (Exception $e) {
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        }
    }


    public function upload(Request $request)
    {
        // dd($file);

        $destination_dir = "../../public/uploads/promo/";
        $base_filename = basename($_FILES["file"]["name"]);
        $temp = explode(".", $_FILES["file"]["name"]);
        $newfilename = round(microtime(true)) . '.' . end($temp);
        $target_file = $destination_dir . $newfilename;

        if(!$_FILES["file"]["error"])
        {
           
            if (move_uploaded_file($_FILES["file"]["tmp_name"], $target_file)) {        
                $response->status = true;
                $response->message = "File uploaded successfully";
                $response->path = 'uploads/promo/'.$newfilename;

            } else {

                $response->status = false;
                $response->message = "File uploading failed";
            }    
        } 
        else
        {
            $response->status = false;
            $response->message = $_FILES["file"]["error"];
        }

    }

    public function kirimPromo(Request $request,$id)
    {
       try {
           foreach ($request->kategory as $key => $value) {
                # code...
                $model = new JobPromo;
                $model->kategori_id = $value;
                $model->promo_id = $id;
                $model->save();
            }
            return redirect()->back()->with('status', 'S');
       } catch (Exception $e) {
           
       }
        
    }

}

resources/views/promo/create.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Buat Promo Baru!</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('promo.store') }}" method="post" enctype="multipart/form-data">
    		@csrf
			  <div class="form-group">
			    <label for="exampleInputName1">Judul</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="judul Reminder" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Deskripsi</label>
			    <textarea class="form-control" name="deskription" placeholder="Isi pesan" rows="5"></textarea>
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('deskription') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Gambar</label>
			    <input type="file" name="gambar" id="exampleInputName1" accept="image/*">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('jml_hari') }}</small>
			     @endif
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection

resources/views/promo/edit.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Edit Promo</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('promo.update',$model->id) }}" method="post" enctype="multipart/form-data">
    		@csrf
    		{{ method_field('PUT') }}
			  <div class="form-group">
			    <label for="exampleInputName1">Judul</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="judul promo" value="{{ $model->judul }}" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Deskripsi</label>
			    <textarea class="form-control" name="deskription" placeholder="Isi pesan" rows="5">{{ $model->keterangan }}</textarea>
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('deskription') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Gambar</label>
			    <input type="file" name="gambar" id="exampleInputName1" accept="image/*">
			    <img src="{{ url($model->gambar) }}" class="img-view" width="200">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('jml_hari') }}</small>
			     @endif
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">

$(document).ready(function(){
	function readURLimage(input,targetimage) {
		if (input.files && input.files[0]) {
		  var reader = new FileReader();
		  
		  reader.onload = function(e) {
		    targetimage.attr('src', e.target.result);
		  }
		  
		  reader.readAsDataURL(input.files[0]); // convert to base64 string
		}
	}
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});

	$('input[name=gambar]').change(function () {
          readURLimage(this,$('.img-view'));
    });
});
</script>

@endsection

resources/views/promo/index.blade.php
 
@extends('layouts.app')

@section('content')
 <!-- Page Heading -->

<!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Promo</h6>
        <a href="{{ route('promo.create') }}" style="float: right;" class="btn btn-info"><i class="fas fa-add"></i>Tambah Baru</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered dataTable table-center" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Judul</th>
                        <th>Keterangan</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                   
                </tbody>
            </table>
        </div>
    </div>
</div>
    

@endsection

@section('scripts')

<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#dataTable').DataTable({
        filter: true,
        processing: true,
        serverSide: true,
        ajax: {
            "url" : '{!! route('promo.index') !!}',
            "type" :"GET"
        },
        columns: [
            {data: 'judul'},
            {data: 'keterangan'},
            {data: 'action',sClass: 'text-center'}

        ]
    });
    $('body').on('click', 'tr .btn-hapus', function () {
        var hapus = confirm('apa anda yakin ingin menghapus ini?');
        var id = $(this).data('id');
        if(hapus){
            $.ajax({
                url: "{{ url('promo')}}/"+id,
                method: "DELETE",
                data: {
                    _token : "{{ csrf_token() }}"
                },
                datatype: "json",
                async: true,
                success: function (msgd) {
                   $("#dataTable").DataTable().ajax.reload();
                },
                error: function (msgd) {
                   
                }

            });
              
        }
      });
});
</script>

@endsection

resources/views/promo/show.blade.php
 
@extends('layouts.app')

@section('content')
<div class="col-lg-12 mb-4">

    <!-- Illustrations -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{$model->judul }}</h6>
        </div>
        <div class="card-body">
            <div class="text-center">
                <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                    src="{{ asset($model->gambar) }}" alt="">
            </div>
            <p>{{ $model->keterangan }}</p>
        </div>
    </div>
    <button class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-fw fa-paper-plane"></i> Kirim Promo </button>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Pilih Target Pasien</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('promo.send',$model->id) }}" method="post">
      @csrf
      <div class="modal-body">
        <?php foreach ($kategory as $key => $value): ?>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="kategory[]" value="{{ $value->id }}">
          <label class="form-check-label" for="defaultCheck1">
            {{ $value->name }} ({{ $value->start }} - {{ $value->end }} minggu)
          </label>
        </div>
        <?php endforeach ?>
        <br>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
        <button type="submit" class="btn btn-primary">Kirim</button>
      </div>
    </div>
     </form>
  </div>
</div>


@endsection

@section('scripts')
<script type="text/javascript">
$(function(){
    @if(session()->has('status') &&  session()->get('status') == 'S')
    Swal.fire({
      position: 'top-end',
      icon: 'success',
      title: 'Success promo berhasil dijadwalkan untuk dikirim.',
      showConfirmButton: false,
      timer: 1500
    });
    @endif
});
</script>
@endsection