routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login-show', 'DashboardController@login_view')->name('login.show');
Route::post('login-web','DashboardController@login_web')->name('login.web');
Auth::routes();

Route::group(['prefix' => '/','middleware' => 'auth:web'], function () {

	Route::get('error-404',function () {
	    return view('error404');
	})->name('error.404');

	Route::get('/', function(){
		return redirect('dashboard');
	});
	
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');
	Route::post('dashboard', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard/promo-bulanan', 'DashboardController@promoKedatangan')->name('dashboard.promo');
	Route::get('dashboard/kedatangan','DashboardController@kedatangan')->name('dashboard.kedatangan');
	Route::get('logout','DashboardController@logout');
	Route::group(['middleware' => 'auth.admin'], function () {
		Route::get('user-admin','AdminController@index');
		Route::get('user-add','AdminController@create');
		Route::post('user-store','AdminController@store')->name('user.store');
		Route::get('user-edit/{id}','AdminController@edit')->name('user.edit');
		Route::post('user-update/{id}','AdminController@update')->name('user.update');
		Route::get('user-deleted/{id}','AdminController@destroy')->name('user.destroy');

		Route::get('setting','SettingController@index');
		Route::post('setting-update/{id}','SettingController@update')->name('setting.update');
		Route::post('setting-keywoo','SettingController@wookey')->name('setting.wookey');
		Route::resource('pasien', 'PasienController');
		Route::post('pasien-add/{id}','PasienController@jadikanPasien')->name('pasien.add');
		
		Route::resource('kategory','KategoryController');
		Route::resource('reminder', 'ReminderController');
		Route::resource('promo','PromoController');

		Route::post('promo-send/{id}','PromoController@kirimPromo')->name("promo.send");

		Route::get("laporan/logPromo",'LaporanController@logPromo')->name("log.promo");
		Route::get("laporan/logRemin",'LaporanController@logReminder')->name("log.remin");



	});
	
});

app/Reminder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reminder extends Model
{
    //
    protected $table = 'reminder';
    protected $primaryKey = 'id';

    public function kategory()
    {
        return $this->belongsTo(KategoryPasien::class,'kategori_id');
    }


}

app/Http/Controllers/ReminderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use App\Reminder;
use App\KategoryPasien;
use Response;

class ReminderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if($request->ajax()){
            $model = Reminder::where('is_deleted','0')->with('kategory');
            $datatables = Datatables::of($model)
            ->addColumn('action', function ($model) {
                return '<a href="'.route('reminder.edit',$model->id).'" class="btn btn-primary btn-circle btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>&nbsp;
                        <button class="btn btn-danger btn-circle btn-sm btn-hapus" data-id="'.$model->id.'">
                            <i class="fas fa-trash"></i>
                        </button>'; 
            });
            return $datatables->make(true);

        }
        return view('reminder.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $kategory = KategoryPasien::where('is_deleted','0')->get();
        return view('reminder.create',compact('kategory'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = new  Reminder();
        $data->nama = $request->name; 
        $data->keterangan = $request->deskription;
        $data->status_kirim = $request->status;
        $data->kategori_id = $request->target_pasien;
        $data->jumlah_hari = $request->jml_hari; 
        if($data->save()){
             return \Redirect::to('/reminder');
        }
        return redirect()->back()->withErrors([
            'others' => "Something went wrong.",
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $model = Reminder::findOrFail($id);
        $kategory = KategoryPasien::where('is_deleted','0')->get();
        return view('reminder.edit',compact('model','kategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        try {
            $model = Reminder::findOrFail($id);
            $model->nama = $request->name; 
            $model->keterangan = $request->deskription;
            $model->status_kirim = $request->status;
            $model->kategori_id = $request->target_pasien;
            $model->jumlah_hari = $request->jml_hari; 
            if($model->save()){
                 return \Redirect::to('/reminder');
            }

            return redirect()->back()->withErrors([
                'others' => "Something went wrong.",
            ]);
        } catch (Exception $e) {
           return redirect()->back()->withErrors([
                'others' => "Something went wrong.",
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {
            $model = Reminder::findOrFail($id);
            $model->is_deleted = 1;
            if($model->save()){
                return Response::json(['status' => 'S','pesan' => 'Berhasil menghapus data.']);
            }
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        } catch (Exception $e) {
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        }
    }
}

resources/views/reminder/create.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Tambah Reminder Baru!</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('reminder.store') }}" method="post">
    		@csrf
			  <div class="form-group">
			    <label for="exampleInputName1">Judul</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="judul Reminder" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Deskripsi</label>
			    <textarea class="form-control" name="deskription" placeholder="Isi pesan reminder" rows="3"></textarea>
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('deskription') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Waktu Kirim</label>
			    <input type="number" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="jml_hari" placeholder="masukan waktu Kirim dalam satuan hari" required max="30" min="1">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('jml_hari') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Status Kirim</label>
			    <div class="form-group">
			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="inlineRadio1" value="1" required>
					    <label class="form-check-label" for="inlineRadio1">Sebelum Kedatangan</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="status" id="inlineRadio2" value="2" required>
					  <label class="form-check-label" for="inlineRadio2">Sesudah Kedatangan</label>
					</div>
			  	</div>
			  </div>

			  <div class="form-group">
			    <label for="exampleInputName1">Target Pasien</label>
			    <select class="form-control" name="target_pasien">
			    	<?php foreach ($kategory as $key => $value): ?>
			    		<option value="{{$value->id}}">{{ $value->name }}</option>
			    	<?php endforeach ?>
			    </select>
			</div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection

resources/views/reminder/edit.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Edit Reminder</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('reminder.update',$model->id) }}" method="POST">
    		@csrf
    		{{ method_field('PUT') }}
			  <div class="form-group">
			    <label for="exampleInputName1">Judul</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="judul Reminder" required value="{{ $model->nama }}">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Deskripsi</label>
			    <textarea class="form-control" name="deskription" placeholder="Isi pesan reminder" rows="3">{{ $model->keterangan }}</textarea>
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('deskription') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Waktu Kirim</label>
			    <input type="number" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="jml_hari" placeholder="masukan waktu Kirim dalam satuan hari" required max="30" min="1" value="{{ $model->jumlah_hari }}">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('jml_hari') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Status Kirim</label>
			    <div class="form-group">
			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="status" id="inlineRadio1" value="1" required @if($model->status_kirim == 'before' ) checked @endif>
					    <label class="form-check-label" for="inlineRadio1">Sebelum Kedatangan</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="status" id="inlineRadio2" value="2" required @if($model->status_kirim == 'after' ) checked @endif>
					  <label class="form-check-label" for="inlineRadio2">Sesudah Kedatangan</label>
					</div>
			  	</div>
			  </div>

			  <div class="form-group">
			    <label for="exampleInputName1">Target Pasien</label>
			    <select class="form-control" name="target_pasien">
			    	<?php foreach ($kategory as $key => $value): ?>

			    		<option value="{{$value->id}}" @if($value->id == $model->kategori_id ) selected @endif>{{ $value->name }}</option>
			    	<?php endforeach ?>
			    </select>
			</div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection

resources/views/reminder/index.blade.php
 
@extends('layouts.app')

@section('content')
 <!-- Page Heading -->

<!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Data Reminder</h6>
        <a href="{{ route('reminder.create') }}" style="float: right;" class="btn btn-info"><i class="fas fa-add"></i>Tambah Baru</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Judul</th>
                        <th>Deskripsi</th>
                        <th>Status Kirim</th>
                        <th>Target Pasien</th>
                        <th>Jumlah Hari</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                
                    
                   
                </tbody>
            </table>
        </div>
    </div>
</div>
    

@endsection

@section('scripts')

<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#dataTable').DataTable({
        filter: true,
        processing: true,
        serverSide: true,
        ajax:{
            "url" : '{!! route("reminder.index") !!}',
            "type" : "GET"
        },
        columns: [
            {data: 'nama'},
            {data: 'keterangan'},
            {
                data: 'status_kirim',
                "render": function (data, type, full) {
                    if (data == "before") {
                         return 'Sebelum Kedatangan';
                    }else{
                         return 'Sesudah Kedatangan';
                    }
                   
                },
                "className": "text-center",

            },
            {data: 'kategory.name'},
            {data: 'jumlah_hari',sClass: 'text-center'},
            {data: 'action',sClass: 'text-center'}

        ]
    });
  $('body').on('click', 'tr .btn-hapus', function () {
    var hapus = confirm('apa anda yakin ingin menghapus ini?');
    var id = $(this).data('id');
    if(hapus){
        $.ajax({
            url: "{{ url('reminder')}}/"+id,
            method: "DELETE",
            data: {
                _token : "{{ csrf_token() }}"
            },
            datatype: "json",
            async: true,
            success: function (msgd) {
               $("#dataTable").DataTable().ajax.reload();
            },
            error: function (msgd) {
               
            }

        });
          
    }
  });
});
</script>

@endsection