routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login-show', 'DashboardController@login_view')->name('login.show');
Route::post('login-web','DashboardController@login_web')->name('login.web');
Auth::routes();

Route::group(['prefix' => '/','middleware' => 'auth:web'], function () {

	Route::get('error-404',function () {
	    return view('error404');
	})->name('error.404');

	Route::get('/', function(){
		return redirect('dashboard');
	});
	
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');
	Route::post('dashboard', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard/promo-bulanan', 'DashboardController@promoKedatangan')->name('dashboard.promo');
	Route::get('dashboard/kedatangan','DashboardController@kedatangan')->name('dashboard.kedatangan');
	Route::get('logout','DashboardController@logout');
	Route::group(['middleware' => 'auth.admin'], function () {
		Route::get('user-admin','AdminController@index');
		Route::get('user-add','AdminController@create');
		Route::post('user-store','AdminController@store')->name('user.store');
		Route::get('user-edit/{id}','AdminController@edit')->name('user.edit');
		Route::post('user-update/{id}','AdminController@update')->name('user.update');
		Route::get('user-deleted/{id}','AdminController@destroy')->name('user.destroy');

		Route::get('setting','SettingController@index');
		Route::post('setting-update/{id}','SettingController@update')->name('setting.update');
		Route::post('setting-keywoo','SettingController@wookey')->name('setting.wookey');
		Route::resource('pasien', 'PasienController');
		Route::post('pasien-add/{id}','PasienController@jadikanPasien')->name('pasien.add');
		
		Route::resource('kategory','KategoryController');
		Route::resource('reminder', 'ReminderController');
		Route::resource('promo','PromoController');

		Route::post('promo-send/{id}','PromoController@kirimPromo')->name("promo.send");

		Route::get("laporan/logPromo",'LaporanController@logPromo')->name("log.promo");
		Route::get("laporan/logRemin",'LaporanController@logReminder')->name("log.remin");



	});
	
});

app/JobPromo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobPromo extends Model
{
    //
    protected $table = 'job_promo';
    protected $primaryKey = 'id';

    public function kategory()
    {
        return $this->belongsTo(KategoryPasien::class,'kategori_id');
    }

    public function promo()
    {
        return $this->belongsTo(NotifPasien::class,'promo_id');
    }
}

app/KategoryPasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class KategoryPasien extends Model
{
    //
    protected $table = 'kategory_pasien';
    protected $primaryKey = 'id';
}

app/Kedatangan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kedatangan extends Model
{
    //
    protected $table = 'kedatangan';
    protected $primaryKey = 'id';
}

app/LogPromo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogPromo extends Model
{
    //
    protected $table = 'log_promo';
    protected $primaryKey = 'id';

}

app/LogRemin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogRemin extends Model
{
    //
    protected $table = 'log_reminder';
    protected $primaryKey = 'id';
}

app/NotifPasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NotifPasien extends Model
{
    //
    protected $table = 'notif_pasien';
    protected $primaryKey = 'id';

}

app/ParamVariable.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class ParamVariable extends Model
{
    //
    protected $table = 'app_parameter';
    protected $primaryKey = 'id';
}

app/ProsesPasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProsesPasien extends Model
{
    //
    protected $table = 'pros_pasien';
    protected $primaryKey = 'id';
}

app/ProsesPasienBaby.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProsesPasienBaby extends Model
{
    //
}

app/ProsesPasienBumil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProsesPasienBumil extends Model
{
    //
}

app/Reminder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reminder extends Model
{
    //
    protected $table = 'reminder';
    protected $primaryKey = 'id';

    public function kategory()
    {
        return $this->belongsTo(KategoryPasien::class,'kategori_id');
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    protected $with = ['hak_akses'];

    /**
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * @return array
     */
    public function getJWTCustomClaims(): array
    {
        return [];
    }

     public function hak_akses()
    {
        return $this->hasOne(UserRole::class,"user_id");
    }
}

app/UserRole.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserRole extends Model
{
    //
    protected $table = 'user_role';
    protected $primaryKey = 'id';

}

app/VwDashboardDatangBulan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardDatangBulan extends Model
{
    //
    
    protected $table = 'vw_datang_bulanan';
}

app/VwDashboardDatangToday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardDatangToday extends Model
{
    //
    protected $table = 'vw_datang_today';
}

app/VwDashboardPasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardPasien extends Model
{
    //
    protected $table = 'vw_dashboard_pasien';
}

app/VwDashboardPromoBulan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardPromoBulan extends Model
{
    //
    protected $table = 'vw_promo_bulanan';
}

app/VwDashboardReminBulan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardReminBulan extends Model
{
    //
    protected $table = 'vw_reminder_today';
}

app/VwDashboardReminToday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VwDashboardReminToday extends Model
{
    //
    protected $table = 'vw_reminder_today';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/error404.blade.php
@extends('layouts.app')

@section('content')
 <!-- 404 Error Text -->
<div class="text-center">
    <div class="error mx-auto" data-text="404">404</div>
    <p class="lead text-gray-800 mb-5">Page Not Found</p>
    <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
    <a href="index.html">&larr; Back to Dashboard</a>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ env('APP_NAME') }} - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/@sweetalert2/theme-material-ui@4/material-ui.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap4.min.css">
    <link href="{{ asset('vendor/js-range/jquery.range.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/datepicker/css/datepicker.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/daterangepicker/daterangepicker.css') }}" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
                <div class="sidebar-brand-icon">
                   <img src="{{ asset('asset/image/logo_lemiel.png') }}">
                </div>
                
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('dashboard') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            @if(\Auth::user()->hak_akses->role == 'admin')
            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>
             <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>User Admin</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Master User:</h6>
                        <a class="collapse-item" href="{{ url('user-admin') }}">Data User</a>
                        <a class="collapse-item" href="{{ url('user-add') }}">Tambah User baru</a>
                    </div>
                </div>
            </li>

            <div class="sidebar-heading">
                Master
            </div>
             <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMaster"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-table""></i>
                    <span>Master Data</span>
                </a>
                <div id="collapseMaster" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Master Data:</h6>
                        <a class="collapse-item" href="{{ route('reminder.index') }}">Reminder</a>
                        <a class="collapse-item" href="{{ url('kategory') }}">Kategori Pasien</a>
                        <a class="collapse-item" href="{{ route('promo.index') }}">Promo</a>
                        <a class="collapse-item" href="{{ route('pasien.index') }}">Pasien</a>
                    </div>
                </div>
            </li>

            @endif
        
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilitiesPeson"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>Laporan</span>
                </a>
                <div id="collapseUtilitiesPeson" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Laporan:</h6>
                        <a class="collapse-item" href="{{ route('log.promo') }}">Log Promo</a>
                        <a class="collapse-item" href="{{ route('log.remin') }}">Reminder</a>
                    </div>
                </div>
            </li>

            
            <li class="nav-item">
                <a class="nav-link" href="{{ url('setting') }}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Setting</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                                <img class="img-profile rounded-circle"
                                    src="{{ asset('img/undraw_profile.svg') }}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @yield('content')

                    

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; {{ env('APP_NAME')}} {{date('Y')}}</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{{ url('logout') }}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.js"></script>
    <script type="text/javascript" src="{{ asset('vendor/daterangepicker/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendor/daterangepicker/daterangepicker.js') }}"></script>

    @yield('scripts')

    <!-- Page level plugins -->
   

   

</body>

</html>

resources/views/notifikasi/kategory.blade.php
 
@extends('layouts.app')

@section('content')
 <!-- Page Heading -->

<!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Kategori Pasien</h6>
        <a href="{{ url('kategory/create') }}" style="float: right;" class="btn btn-info"><i class="fas fa-add"></i>Tambah Baru</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered dataTable table-center" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Judul</th>
                        <th>Keterangan</th>
                        <th>Pasien</th>
                        <th>Target usia (Minggu)</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                   
                </tbody>
            </table>
        </div>
    </div>
</div>
    

@endsection

@section('scripts')

<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#dataTable').DataTable({
        filter: true,
        processing: true,
        serverSide: true,
        ajax: {
            "url" : '{!! route('kategory.index') !!}',
            "type" :"GET"
        },
        columns: [
            {data: 'name'},
            {data: 'deskription'},
            {
                data: 'jenis',
                "render": function (data, type, full) {
                    if (data == 'bumil') {
                         return 'Ibu hamil';
                    }else{
                         return 'Bayi';
                    }
                   
                },
                "className": "text-center",

            },
            {
                "render": function (data, type, full) {
                    return full.start+" - "+full.end+" Minggu"
                   
                },
                "className": "text-center",

            },
            {data: 'action',sClass: 'text-center'}

        ]
    });
    $('body').on('click', 'tr .btn-hapus', function () {
        var hapus = confirm('apa anda yakin ingin menghapus ini?');
        var id = $(this).data('id');
        if(hapus){
            $.ajax({
                url: "{{ url('kategory')}}/"+id,
                method: "DELETE",
                data: {
                    _token : "{{ csrf_token() }}"
                },
                datatype: "json",
                async: true,
                success: function (msgd) {
                   $("#dataTable").DataTable().ajax.reload();
                },
                error: function (msgd) {
                   
                }

            });
              
        }
      });
});
</script>

@endsection

resources/views/notifikasi/kategory_create.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Tambah Kategori Pasien Baru!</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('kategory.store') }}" method="post">
    		@csrf
			  <div class="form-group">
			    <label for="exampleInputName1">Nama</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="masukan nama kategory" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Keterangan</label>
			    <textarea class="form-control" name="deskription" placeholder="Beri penjelasan kategori ini" rows="3"></textarea>
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('deskription') }}</small>
			     @endif
			  </div>
			  
			  <div class="form-group">
			    <label for="exampleInputEmail1">Jenis Pasien</label>
			    <div class="form-group">

			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="jenis" id="inlineRadio1" value="bumil" required>
					    <label class="form-check-label" for="inlineRadio1">Ibu Hamil</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="jenis" id="inlineRadio2" value="bayi" required>
					  <label class="form-check-label" for="inlineRadio2">Bayi</label>
					</div>
				
			  	</div>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Target Pasien</label>
			    <div class="form-group">

			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="type" id="inlineRadio3" value="Calon Pasien" required>
					    <label class="form-check-label" for="inlineRadio1">Calon Pasien</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="type" id="inlineRadio4" value="Pasien" required>
					  <label class="form-check-label" for="inlineRadio2">Pasien</label>
					</div>
				
			  	</div>
			  </div>
			  <div class="form-group" style="margin-bottom: 50px">
			    <label for="exampleInputEmail1" style="margin-bottom: 30px">Target Usia</label>
			    <br>
			    <input type="hidden" class="range-slider" name="range" value="23" />
			    @if ($errors->has('deskription'))
			     <small  class="form-text text-danger">{{ $errors->first('range') }}</small>
			     @endif
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection