routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login-show', 'DashboardController@login_view')->name('login.show');
Route::post('login-web','DashboardController@login_web')->name('login.web');
Auth::routes();

Route::group(['prefix' => '/','middleware' => 'auth:web'], function () {

	Route::get('error-404',function () {
	    return view('error404');
	})->name('error.404');

	Route::get('/', function(){
		return redirect('dashboard');
	});
	
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');
	Route::post('dashboard', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard/promo-bulanan', 'DashboardController@promoKedatangan')->name('dashboard.promo');
	Route::get('dashboard/kedatangan','DashboardController@kedatangan')->name('dashboard.kedatangan');
	Route::get('logout','DashboardController@logout');
	Route::group(['middleware' => 'auth.admin'], function () {
		Route::get('user-admin','AdminController@index');
		Route::get('user-add','AdminController@create');
		Route::post('user-store','AdminController@store')->name('user.store');
		Route::get('user-edit/{id}','AdminController@edit')->name('user.edit');
		Route::post('user-update/{id}','AdminController@update')->name('user.update');
		Route::get('user-deleted/{id}','AdminController@destroy')->name('user.destroy');

		Route::get('setting','SettingController@index');
		Route::post('setting-update/{id}','SettingController@update')->name('setting.update');
		Route::post('setting-keywoo','SettingController@wookey')->name('setting.wookey');
		Route::resource('pasien', 'PasienController');
		Route::post('pasien-add/{id}','PasienController@jadikanPasien')->name('pasien.add');
		
		Route::resource('kategory','KategoryController');
		Route::resource('reminder', 'ReminderController');
		Route::resource('promo','PromoController');

		Route::post('promo-send/{id}','PromoController@kirimPromo')->name("promo.send");

		Route::get("laporan/logPromo",'LaporanController@logPromo')->name("log.promo");
		Route::get("laporan/logRemin",'LaporanController@logReminder')->name("log.remin");



	});
	
});

app/Http/Controllers/Api/PasienController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\ProsesPasien;
use App\ParamVariable;
use App\Kedatangan;
use Carbon\Carbon;
use Auth;

class PasienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $pasien = ProsesPasien::where(['is_deleted' => 0,'is_pasien' => 'Pasien']);

        if ($request->has('jenis') && $request->jenis != "all") {
            # code...
            $pasien = $pasien->where('jenis', $request->jenis);
        }
        if($request->_q != '')
        {
            $q = $request->_q;
            # code...
            $pasien =$pasien->whereRaw("upper(nama) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(no_wa) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(usia_kehamilan) LIKE '%".strtoupper($q)."%'");
        }
        $pasien = $pasien->orderBy("created_at","desc")->paginate(7);
        return response()->json(compact('pasien'), 200);
    }

    public function calon(Request $request)
    {
        //
        $pasien = ProsesPasien::where(['is_deleted' => 0,'is_pasien' => 'Calon Pasien']);

        if ($request->has('jenis') && $request->jenis != "all") {
            # code...
            $pasien = $pasien->where('jenis', $request->jenis);
        }
        if($request->_q != '')
        {
            $q = $request->_q;
            # code...
            $pasien =$pasien->whereRaw("upper(nama) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(no_wa) LIKE '%".strtoupper($q)."%'")
            ->orWhereRaw("upper(usia_kehamilan) LIKE '%".strtoupper($q)."%'");
        }
        $pasien = $pasien->orderBy("created_at","desc")->paginate(7);
        return response()->json(compact('pasien'), 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        //
        $model = ProsesPasien::findOrFail($request->id);
        $model->last_visit = Carbon::now();
        $model->note = $request->note;
        $model->is_pasien = 'Pasien';
        $model->updated_by = Auth::user()->id;
        if($model->save()){
            $kedatangan = new Kedatangan;
            $kedatangan->tgl_datang = Carbon::now();
            $kedatangan->id_pasien = $model->id;
            $kedatangan->is_arrival = 1;
            $kedatangan->save();
            return response()->json(compact('model'), 200);
        }
        return response()->json(compact('model'), 500);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        try {
            $model = new ProsesPasien();
            $model->nama = $request->nama;
            $model->no_wa = $request->no_wa;
            $model->jenis = $request->jenis;

            if($model->jenis == 'bumil')
            {
                $param = ParamVariable::where('var3','max_birth')->first();
                $minggu = $param->var1 - $request->usia;
                $hari = Carbon::now()->addDays($minggu*7);
                $model->usia_kehamilan =  $request->usia;
                $model->usia_kehamilan_calc =  $request->usia;
                $model->hpl = $hari;
            }else{
                $model->usia_bayi =  $request->usia;
                $model->usia_bayi_calc =  $request->usia;
            }

            $model->tgl_daftar = Carbon::now();
            $model->created_by = Auth::user()->id;
            $model->updated_by = Auth::user()->id;
            $model->save();

            return response()->json(['message' => 'Created Success','data' =>  $model ], 201);
            
        } catch (Exception $e) {
            return response()->json(['message' => 'error. '.$e->getMassage() ,'data' => $e ], 500);
        }
        return response()->json(['message' => 'Something went wrong. '], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
         try {
            $model = ProsesPasien::findOrFail($request->id);
            $model->nama = $request->name;
            $model->no_wa = $request->wa;
            $model->jenis = $request->jenis;
            if($model->jenis == 'bumil')
            {
                $param = ParamVariable::where('var3','max_birth')->first();
                $minggu = $param->var1 - $request->usia;
                $hari = Carbon::now()->addDays($minggu*7);
                $model->usia_kehamilan =  $request->usia;
                $model->usia_kehamilan_calc =  $request->usia;
                $model->hpl = $hari;
            }else{
                $model->usia_bayi =  $request->usia;
                $model->usia_bayi_calc =  $request->usia;
            }
            $model->updated_by = Auth::user()->id;
            $model->save();
            return response()->json(['message' => 'Updated Success','data' =>  $model ], 200);
            
        } catch (Exception $e) {
            return response()->json(['message' => 'error. '.$e->getMassage() ,'data' => $e ], 500);
        }
        return response()->json(['message' => 'Something went wrong. '], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //

        $model = ProsesPasien::findOrFail($request->id);
        $model->is_deleted = 1;
        $model->save();

    }
}

app/Http/Controllers/PasienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ProsesPasien;
use Yajra\DataTables\Facades\DataTables;
use App\ParamVariable;
use Carbon\Carbon;
use Auth;
use DB;
use Response;
use App\Kedatangan;

class PasienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //

        if($request->ajax()){
            $model = ProsesPasien::where('is_deleted',0);
            $datatables = Datatables::of($model)
            ->addColumn('action', function ($model) {
                return '<a href="'.route('pasien.show',$model->id).'" class="btn btn-primary btn-circle btn-sm">
                            <i   class="fas fa-eye"></i>
                        </a>&nbsp;<a href="'.route('pasien.edit',$model->id).'" class="btn btn-primary btn-circle btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>
                        <button class="btn btn-danger btn-circle btn-sm btn-hapus" data-id="'.$model->id.'">
                            <i class="fas fa-trash"></i>
                        </button>'; 
            });
            return $datatables->make(true);

        }
        return view('pasien.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('pasien.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());
        $model = new ProsesPasien();
        $model->nama = $request->name;
        $model->no_wa = $request->wa;
        $model->jenis = $request->jenis;

        if($model->jenis == 'bumil')
        {
            $param = ParamVariable::where('var3','max_birth')->first();
            $minggu = $param->var1 - $request->usia;
            $hari = Carbon::now()->addDays($minggu*7);
            $model->usia_kehamilan =  $request->usia;
            $model->usia_kehamilan_calc =  $request->usia;
            $model->hpl = $hari;
        }else{
            $model->usia_bayi =  $request->usia;
            $model->usia_bayi_calc =  $request->usia;
        }

        $model->tgl_daftar = Carbon::now();
        $model->created_by = Auth::user()->id;
        $model->updated_by = Auth::user()->id;
        $model->save();

        if($model->save()){
            return \Redirect::to('/pasien');
        }
        return redirect()->back()->withErrors([
            'others' => "Something went wrong.",
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $model = ProsesPasien::findOrFail($id);
        return view('pasien.show',compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $model = ProsesPasien::findOrFail($id);
        return view('pasien.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $model = ProsesPasien::findOrFail($id);
        $model->nama = $request->name;
        $model->no_wa = $request->wa;
        $model->jenis = $request->jenis;

        if($model->jenis == 'bumil')
        {
            $param = ParamVariable::where('var3','max_birth')->first();
            $minggu = $param->var1 - $request->usia;
            $hari = Carbon::now()->addDays($minggu*7);
            $model->usia_kehamilan =  $request->usia;
            $model->usia_kehamilan_calc =  $request->usia;
            $model->hpl = $hari;
        }else{
            $model->usia_bayi =  $request->usia;
            $model->usia_bayi_calc =  $request->usia;
        }
        $model->updated_by = Auth::user()->id;
        $model->save();

        if($model->save()){
            return \Redirect::to('/pasien');
        }
        return redirect()->back()->withErrors([
            'others' => "Something went wrong.",
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {
            $model = ProsesPasien::findOrFail($id);
            $model->is_deleted = 1;
            if($model->save()){
                return Response::json(['status' => 'S','pesan' => 'Berhasil menghapus data.']);
            }
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        } catch (Exception $e) {
            return Response::json(['status' => 'E','pesan' => 'Gagal menghapus data.']);
        }
    }

    public function jadikanPasien(Request $request,$id)
    {
        try {
            $model = ProsesPasien::findOrFail($id);
            $model->last_visit = Carbon::now();
            $model->note = $request->note;
            $model->is_pasien = 'Pasien';
            $model->updated_by = Auth::user()->id;
            if($model->save()){
                $kedatangan = new Kedatangan;
                $kedatangan->tgl_datang = Carbon::now();
                $kedatangan->id_pasien = $model->id;
                $kedatangan->is_arrival = 1;
                $kedatangan->save();
                return redirect()->back()->with('status', 'S');
            }
            return redirect()->back()->with('status', 'E');
            
        } catch (Exception $e) {
            return redirect()->back()->with('status', 'E');
        }

    }
}

resources/views/pasien/create.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Calon Pasien Baru!</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('pasien.store') }}" method="post" enctype="multipart/form-data">
    		@csrf
			  <div class="form-group">
			    <label for="exampleInputName1">Nama</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="Nama pasien" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Nomor WhatsApp</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="wa" placeholder="08xxx" required>
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('wa') }}</small>
			     @endif
			  </div>
			  
			  <div class="form-group">
			    <label for="exampleInputName1">Usia (Minggu)</label>
			    <input type="number" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="usia" placeholder="masukan usia kehamilan/bayi" required  min="1">
			     @if ($errors->has('usia'))
			     <small  class="form-text text-danger">{{ $errors->first('usia') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Jenis</label>
			    <div class="form-group">
			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="jenis" id="inlineRadio1" value="bumil" required>
					    <label class="form-check-label" for="inlineRadio1">Ibu Hamil</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="jenis" id="inlineRadio2" value="bayi" required>
					  <label class="form-check-label" for="inlineRadio2">Bayi</label>
					</div>
				
			  	</div>
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection

resources/views/pasien/edit.blade.php
@extends('layouts.app')

@section('content')
 	<div class="text-left">
        <h1 class="h4 text-gray-900 mb-4">Edit Calon Pasien!</h1>
    </div>
    <hr>
    @if ($errors->has('others'))
    <div class="alert alert-danger" role="alert" style="margin-left: 32px;margin-right: 32px;">
		  {{ $errors->first('others') }}
	</div>
	@endif
    <div class="col-md-8">
    	<form action="{{ route('pasien.update',$model->id) }}" method="post" enctype="multipart/form-data">
    		@csrf
    		{{ method_field('PUT') }}
			  <div class="form-group">
			    <label for="exampleInputName1">Nama</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="name" placeholder="Nama pasien" required value="{{ $model->nama }}">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('name') }}</small>
			     @endif
			  </div>
			  <div class="form-group">
			    <label for="exampleInputName1">Nomor WhatsApp</label>
			    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="wa" placeholder="08xxx" required value="{{ $model->no_wa }}">
			     @if ($errors->has('name'))
			     <small  class="form-text text-danger">{{ $errors->first('wa') }}</small>
			     @endif
			  </div>
			  
			  <div class="form-group">
			    <label for="exampleInputName1">Usia (Minggu)</label>
			    @if($model->jenis == 'bumil')
			    <input type="number" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="usia" placeholder="masukan usia kehamilan/bayi" required  min="1" value="{{ $model->usia_kehamilan_calc }}">
			    @else
			    <input type="number" class="form-control" id="exampleInputName1" aria-describedby="emailHelp" name="usia" placeholder="masukan usia kehamilan/bayi" required  min="1" value="{{ $model->usia_bayi_calc }}">
			    @endif
			     @if ($errors->has('usia'))
			     <small  class="form-text text-danger">{{ $errors->first('usia') }}</small>
			     @endif
			  </div>
			  <div class="form-group">

			    	<div class="form-check form-check-inline">
						<input class="form-check-input" type="radio" name="jenis" id="inlineRadio1" value="bumil" required @if($model->jenis == 'bumil' ) checked @endif>
					    <label class="form-check-label" for="inlineRadio1">Ibu Hamil</label>
					</div>
					<div class="form-check form-check-inline">
					  <input class="form-check-input" type="radio" name="jenis" id="inlineRadio2" value="bayi" required @if($model->jenis == 'bayi' ) checked @endif>
					  <label class="form-check-label" for="inlineRadio2">Bayi</label>
					</div>
				
			  	</div>
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
    </div>
    
@endsection

@section('scripts')
<script src="{{ asset('vendor/js-range/jquery.range.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.range-slider').jRange({
	    from: 0,
	    to: 100,
	    step: 1,
	    scale: [0,25,50,75,100],
	    format: '%s',
	    width: 600,
	    showLabels: true,
	    isRange : true
	});
});
</script>

@endsection

resources/views/pasien/index.blade.php
 
@extends('layouts.app')

@section('content')
 <!-- Page Heading -->

<!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Data Pasien</h6>
        <a href="{{ route('pasien.create') }}" style="float: right;" class="btn btn-info"><i class="fas fa-add"></i>Tambah Baru</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>No Wa</th>
                        <th>Usia (Minggu)</th>
                        <th>Jenis</th>
                        <th>Status</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                   
                </tbody>
            </table>
        </div>
    </div>
</div>
    

@endsection

@section('scripts')

<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#dataTable').DataTable({
        filter: true,
        processing: true,
        serverSide: true,
        ajax: '{!! url('pasien') !!}',
        columns: [
            {data: 'nama'},
            {data: 'no_wa'},
            {
                data: 'jenis',
                "render": function (data, type, full) {
                    if (data == "bumil") {
                         return full.usia_kehamilan_calc;
                    }else{
                         return full.usia_bayi_calc;
                    }
                   
                },
                "className": "text-center",

            },
            {data: 'jenis'},
            {data: 'is_pasien'},
            {data: 'action',className:"text-center"}

        ]
    });
    $('body').on('click', 'tr .btn-hapus', function () {
        var hapus = confirm('apa anda yakin ingin menghapus ini?');
        var id = $(this).data('id');
        if(hapus){
            $.ajax({
                url: "{{ url('pasien')}}/"+id,
                method: "DELETE",
                data: {
                    _token : "{{ csrf_token() }}"
                },
                datatype: "json",
                async: true,
                success: function (msgd) {
                   $("#dataTable").DataTable().ajax.reload();
                },
                error: function (msgd) {
                   
                }

            });
              
        }
      });
});

</script>

@endsection

resources/views/pasien/show.blade.php
 
@extends('layouts.app')

@section('content')


  <!-- Illustrations -->
  <div class="card shadow mb-4">
      <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Detail Pasien</h6>
          <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                  aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">AKSI:</div>
                  @if($model->is_pasien == 'Calon Pasien')
                  <button class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-plus"></i> Pasien</button>
                  @else
                  <button class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-tasks"></i> Visit</button>
                  @endif
                  <a class="dropdown-item" href="{{ route('pasien.edit',$model->id) }}"><i class="fas fa-edit"></i> Ubah</a>
                  <div class="dropdown-divider"></div>
                  <button class="dropdown-item" id="btn-hapus" style="color: red"><i class="fas fa-trash"></i> Hapus</button>
              </div>
          </div>
      </div>
      <div class="card-body">
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Nama</label>
            <div class="col-sm-8">
              <label for="staticEmail" class="form-control-plaintext">{{ $model->nama }}</label>
              
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Nomor WhatsApp</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->no_wa }}</label>
              
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Jenis</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->jenis == 'bumil' ? 'Ibu Hamil' : 'Bayi' }}</label>
             
            </div>
          </div>

          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Status</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->is_pasien }}</label>
            </div>
          </div>
          @if($model->jenis == 'bumil')
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Usia Awal</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->usia_kehamilan }} minggu</label>
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Usia saat ini</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->usia_kehamilan_calc }} minggu</label>
            </div>
          </div>
          @else

          @endif
          @if($model->jenis == 'bumil')
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Status Persalinan</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->is_persalinan == 1 ? 'Sudah' : 'Belum' }}</label>
            </div>
          </div>
          @endif
          @if($model->is_pasien == 'Pasien')
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Terakhir Datang</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->last_visit }}</label>
            </div>
          </div>
          @endif
          @if($model->is_pasien == 'Pasien')
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label font-weight-bold">Catatan</label>
            <div class="col-sm-8">
               <label for="staticEmail" class="form-control-plaintext">{{ $model->note }}</label>
            </div>
          </div>
          @endif
      </div>
  </div>
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        @if($model->is_pasien == 'Calon Pasien')
        <h5 class="modal-title" id="exampleModalLongTitle"><i class="fas fa-plus"></i> Pasien</h5>
        @else
        <h5 class="modal-title" id="exampleModalLongTitle"><i class="fas fa-tasks"></i> Visit</h5>
        @endif
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('pasien.add',$model->id) }}" method="post">
      @csrf
      <div class="modal-body">
        <div class="form-group">
            <label for="exampleInputName1">Catatan Pasien:</label>
            <textarea class="form-control" rows="4" name="note">{{ $model->note }}</textarea>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
        <button type="submit" class="btn btn-primary">Kirim</button>
      </div>
    </div>
     </form>
  </div>
</div>



@endsection

@section('scripts')
<script type="text/javascript">
$(function(){
    @if(session()->has('status') &&  session()->get('status') == 'S')
    Swal.fire({
      position: 'top-end',
      icon: 'success',
      title: 'Success berhasil melakukan perubahan.',
      showConfirmButton: false,
      timer: 1500
    });
    @endif

    $('#btn-hapus').click(function () {
        var hapus = confirm('apa anda yakin ingin menghapus ini?');
        if(hapus){
            $.ajax({
                url: "{{ url('pasien')}}/{{$model->id}}",
                method: "DELETE",
                data: {
                    _token : "{{ csrf_token() }}"
                },
                datatype: "json",
                async: true,
                success: function (msgd) {
                   Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: msgd.pesan,
                    showConfirmButton: false,
                    timer: 1500
                  });
                   window.location.href="{{ url('pasien') }}";
                },
                error: function (msgd) {
                   
                }

            });
              
        }
      });
});
</script>
@endsection